/// Flutter and native dependency license collection for consumer applications.
///
/// The package merges Flutter's [LicenseRegistry] with Android Gradle,
/// CocoaPods, and remote Swift Package Manager metadata generated during native
/// builds. Use [registerNativeLicenses] with Flutter's standard license page or
/// [loadMergedLicenses] for a custom UI or export.
library;

import 'package:flutter/foundation.dart';

import 'src/license_service.dart';
import 'src/merged_license_entry.dart';

export 'src/merged_license_entry.dart';

final LicenseService _licenseService = LicenseService();

/// Returns one deterministic snapshot of Flutter and native license notices.
///
/// Flutter framework, engine, package, and asset notices come from
/// [LicenseRegistry]. Android, iOS, and macOS notices come from the payload
/// generated by the package's build integration. Identical texts are grouped,
/// package names are trimmed and sorted, and the returned list cannot be
/// modified.
/// Flutter-origin text is reconstructed from the formatted paragraphs exposed
/// by [LicenseRegistry]; native payload strings are kept exactly.
///
/// On web, Linux, and Windows, this returns the entries already exposed by
/// Flutter without attempting to load a native payload. Additional notice
/// files declared with Flutter's `licenses` pubspec field are included there.
Future<List<MergedLicenseEntry>> loadMergedLicenses() {
  return _licenseService.loadMergedLicenses();
}

/// Adds generated Android, iOS, and macOS notices to Flutter's
/// [LicenseRegistry].
///
/// Registration is lazy and idempotent. Calling this more than once adds one
/// collector, and the native payload is loaded only if the registry is read.
/// This is useful for apps that display Flutter's standard Material license
/// page instead of rendering the result of [loadMergedLicenses] themselves.
///
/// This does nothing on web, Linux, and Windows because those platforms use
/// Flutter's registry directly.
void registerNativeLicenses() {
  _licenseService.registerNativeLicenses();
}
