#!/bin/sh
set -eu

package_name='flutter_native_oss_licenses'
expected_origin_https='https://github.com/BasalBit/flutter_native_oss_licenses.git'
expected_origin_ssh='git@github.com:BasalBit/flutter_native_oss_licenses.git'
package_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)

die() {
  printf 'Release stopped: %s\n' "$*" >&2
  exit 1
}

usage() {
  printf 'Usage: %s check|publish\n' "${0##*/}" >&2
  exit 64
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"
}

read_pubspec_version() {
  awk '/^version:[[:space:]]*/ { print $2; exit }' pubspec.yaml
}

read_changelog_version() {
  sed -n -E 's/^## ([0-9]+\.[0-9]+\.[0-9]+)$/\1/p' CHANGELOG.md | head -n 1
}

read_podspec_version() {
  sed -n -E "s/^[[:space:]]*s\.version[[:space:]]*=[[:space:]]*'([^']+)'/\1/p" "$1" | head -n 1
}

read_example_lock_version() {
  awk '
    /^  flutter_native_oss_licenses:$/ { in_package = 1; next }
    in_package && /^  [^ ]/ { in_package = 0 }
    in_package && /^[[:space:]]+version:[[:space:]]*/ {
      gsub(/"/, "", $2)
      print $2
      exit
    }
  ' example/pubspec.lock
}

assert_equal() {
  [ "$1" = "$2" ] || die "$3: expected $1, found ${2:-missing}"
}

assert_clean_worktree() {
  status_output=$(git status --porcelain --untracked-files=all)
  [ -z "$status_output" ] || die "the Git worktree must be clean"
}

assert_repository_state() {
  [ "$(uname -s)" = 'Darwin' ] || die 'manual publishing is supported only on macOS'
  assert_equal "$package_root" "$(git rev-parse --show-toplevel)" 'repository root'

  origin_url=$(git remote get-url origin)
  case "$origin_url" in
    "$expected_origin_https" | "$expected_origin_ssh") ;;
    *) die 'origin does not point to BasalBit/flutter_native_oss_licenses' ;;
  esac

  assert_equal 'main' "$(git branch --show-current)" 'current branch'
  assert_clean_worktree

  git fetch --prune origin main
  assert_equal "$(git rev-parse origin/main)" "$(git rev-parse HEAD)" \
    'local main must match origin/main'
}

assert_version_state() {
  version=$(read_pubspec_version)
  printf '%s\n' "$version" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$' ||
    die 'pubspec version must use stable X.Y.Z format'

  assert_equal "$version" "$(read_changelog_version)" 'changelog version'
  assert_equal "$version" "$(read_podspec_version ios/flutter_native_oss_licenses.podspec)" \
    'iOS podspec version'
  assert_equal "$version" "$(read_podspec_version macos/flutter_native_oss_licenses.podspec)" \
    'macOS podspec version'
  assert_equal "$version" "$(read_example_lock_version)" 'example lockfile version'

  expected_header="// Generated by flutter_native_oss_licenses $version. Rerun setup after upgrades."
  grep -Fqx "$expected_header" tool/templates/flutter_native_oss_licenses.gradle ||
    die 'Android template version is not synchronized'
  cmp -s tool/templates/flutter_native_oss_licenses.gradle \
    example/android/flutter_native_oss_licenses.gradle ||
    die 'Android template and example copy differ'
}

assert_official_pub_host() {
  case "${PUB_HOSTED_URL-}" in
    '' | 'https://pub.dev' | 'https://pub.dev/') ;;
    *) die 'PUB_HOSTED_URL must be unset or point to https://pub.dev' ;;
  esac
  unset PUB_HOSTED_URL
}

assert_version_unpublished() {
  status_code=$(curl --silent --show-error \
    --connect-timeout 10 \
    --max-time 30 \
    --output /dev/null \
    --write-out '%{http_code}' \
    "https://pub.dev/api/packages/$package_name/versions/$version")

  case "$status_code" in
    404) ;;
    200) die "$package_name $version is already published" ;;
    *) die "pub.dev version check returned HTTP $status_code" ;;
  esac
}

assert_release_tag_absent() {
  git show-ref --verify --quiet "refs/tags/v$version" &&
    die "local tag v$version already exists"
  git ls-remote --exit-code --tags origin "refs/tags/v$version" >/dev/null 2>&1 &&
    die "remote tag v$version already exists"
  return 0
}

run_gate() {
  sh "$package_root/tool/verify_pub_points.sh"
  assert_clean_worktree
}

[ "$#" -eq 1 ] || usage
mode=$1
case "$mode" in
  check | publish) ;;
  *) usage ;;
esac

for command_name in awk cmp curl dart flutter git grep head sed sh uname; do
  require_command "$command_name"
done

cd "$package_root"
assert_repository_state
assert_version_state
assert_official_pub_host

if [ "$mode" = 'check' ]; then
  run_gate
  printf '\n%s %s passed the publication checks.\n' "$package_name" "$version"
  exit 0
fi

[ -t 0 ] && [ -t 1 ] || die 'publishing requires an interactive terminal'
assert_version_unpublished
assert_release_tag_absent
run_gate
assert_version_unpublished
assert_release_tag_absent

printf '\nPublishing %s %s interactively to https://pub.dev.\n' \
  "$package_name" "$version"
printf '%s\n' \
  'Dart handles authentication. This script does not read or store credentials.' \
  'Review the archive and confirm the prompt from dart pub publish.'

dart pub publish

printf '\nPublished %s %s. No Git tag was created.\n' "$package_name" "$version"
